export const pagesRoutes = [
  ["v-8daa1a0e","/",{"y":"h","t":"Decentralized Micro Blogging Association","i":"icon-home"},["/README.md"]],
  ["v-45a132b4","/about/contact.html",{"y":"a","t":"contact","i":"more"},[":md"]],
  ["v-2da080cb","/governance/organisation.html",{"y":"a","t":"organisation","i":"build"},[":md"]],
  ["v-25af87be","/governance/statement.html",{"y":"a","t":"mission statement","i":"build"},[":md"]],
  ["v-c716507c","/blog/whitepaper.html",{"y":"a","t":"Reloading Secure Scuttlebut","i":"config"},[":md"]],
  ["v-0ab1dcb2","/projects/delog.html",{"y":"a","t":"delog","i":"android"},[":md"]],
  ["v-24fe54af","/projects/ssb-relay.html",{"y":"a","t":"ssb-relay","i":"any"},[":md"]],
  ["v-3b4ac56c","/specs/features.html",{"y":"a","t":"Features","i":"define","O":1},[":md"]],
  ["v-eb9f481e","/specs/protocol.html",{"y":"a","t":"Protocol","i":"api","O":2},[":md"]],
  ["v-61bdca3f","/specs/spip-01.html",{"y":"a","t":"invite-code client flow","i":"enum","O":11},[":md"]],
  ["v-6372a2de","/specs/spip-02.html",{"y":"a","t":"message flow","i":"enum","O":12},[":md"]],
  ["v-65277b7d","/specs/spip-03.html",{"y":"a","t":"decentralized identifier","i":"enum","O":13},[":md"]],
  ["v-3706649a","/404.html",{"y":"p","t":""},[]],
  ["v-74bc627b","/about/",{"y":"p","t":"About"},[]],
  ["v-ac914418","/governance/",{"y":"p","t":"Governance"},[]],
  ["v-145ac574","/blog/",{"y":"p","t":"Blog"},[]],
  ["v-6dc367c8","/projects/",{"y":"p","t":"Projects"},[]],
  ["v-d797d160","/specs/",{"y":"p","t":"Specs"},[]],
]
